# Generated by Django 4.2.10 on 2025-09-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logsheet',
            name='visual_log_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
